
dotnet-rgit --cmd compute-loss --selected-reviewers-type core --simulation-first-period 1 --mega-pr-size 100 --save-strategy nothing
dotnet-rgit --cmd compute-loss --selected-reviewers-type core --simulation-first-period 1 --mega-pr-size 100 --save-strategy reviewers-actual
dotnet-rgit --cmd compute-loss --selected-reviewers-type all --simulation-first-period 1 --mega-pr-size 100 --save-strategy bird --pullRequests-reviewer-selection "0:nothing-nothing,1:replace-1,2:replace-1,-:replace-1"
dotnet-rgit --cmd compute-loss --selected-reviewers-type all --simulation-first-period 1 --mega-pr-size 100 --save-strategy random --pullRequests-reviewer-selection "0:nothing-nothing,1:replace-1,2:replace-1,-:replace-1"
dotnet-rgit --cmd compute-loss --selected-reviewers-type all --simulation-first-period 1 --mega-pr-size 100 --save-strategy review --pullRequests-reviewer-selection "0:nothing-nothing,1:replace-1,2:replace-1,-:replace-1"
dotnet-rgit --cmd compute-loss --selected-reviewers-type all --simulation-first-period 1 --mega-pr-size 100 --save-strategy commit --pullRequests-reviewer-selection "0:nothing-nothing,1:replace-1,2:replace-1,-:replace-1"
dotnet-rgit --cmd compute-loss --selected-reviewers-type all --simulation-first-period 1 --mega-pr-size 100 --save-strategy line --pullRequests-reviewer-selection "0:nothing-nothing,1:replace-1,2:replace-1,-:replace-1"
dotnet-rgit --cmd compute-loss --selected-reviewers-type all --simulation-first-period 1 --mega-pr-size 100 --save-strategy spreading --pullRequests-reviewer-selection "0:nothing-nothing,1:replace-1,2:replace-1,-:replace-1"
dotnet-rgit --cmd compute-loss --selected-reviewers-type all --simulation-first-period 1 --mega-pr-size 100 --save-strategy persist --pullRequests-reviewer-selection "0:nothing-nothing,1:replace-1,2:replace-1,-:replace-1"
dotnet-rgit --cmd compute-loss --selected-reviewers-type all --simulation-first-period 1 --mega-pr-size 100 --save-strategy persist-spreading --pullRequests-reviewer-selection "0:nothing-nothing,1:replace-1,2:replace-1,-:replace-1"