dotnet-rgit --cmd get-github-pullrequests  --conf-path "C:\Users\s_irsaee\Documents\relationalgit_corefx2.json" 
dotnet-rgit --cmd get-github-pullrequest-reviewers  --conf-path "C:\Users\s_irsaee\Documents\relationalgit_corefx2.json"
dotnet-rgit --cmd get-github-pullrequest-reviewer-comments  --conf-path "C:\Users\s_irsaee\Documents\relationalgit_corefx2.json"
dotnet-rgit --cmd get-github-pullrequests-files  --conf-path "C:\Users\s_irsaee\Documents\relationalgit_corefx2.json"
dotnet-rgit --cmd get-merge-events  --conf-path "C:\Users\s_irsaee\Documents\relationalgit_corefx2.json"
dotnet-rgit --cmd get-pullrequest-issue-comments  --conf-path "C:\Users\s_irsaee\Documents\relationalgit_corefx2.json"
dotnet-rgit --cmd map-git-github-names  --conf-path "C:\Users\s_irsaee\Documents\relationalgit_corefx2.json"